### ISSUE TITLE
Popovers don't work when rendering multiple instances of VPV

### ISSUE THREAD

**Issue by bringmethedeathstar** [vue-pdf-viewer/vue-pdf-viewer#7]
When loading two or more VPV components on the same page, only the first instance has functioning popovers (search/zoom/other options).

[![Image from Gyazo](https://i.gyazo.com/9f904efe7183844e45d3a10abd8b3c68.gif)](https://gyazo.com/9f904efe7183844e45d3a10abd8b3c68)

**Comment by bringmethedeathstar** [comment]
1. Node Version => `18.20.3`
2. Vue Version  => `3.2.45` (Nuxt `3.11.2`)
3. Style package (such as tailwind or others) => TailwindCSS `3.4.3`
4. pdfjs-dist version => `3.11.174`

I'll try and make a simple reproduction on Codepen when I get some time 🤞🏻

**Comment by ansonchieng** [comment]
@bringmethedeathstar Thanks for the update! Sorry we couldn’t identify the issue on our end. If you come across any new information or run into other issues, feel free to reach out. We’d be happy to help you take another look!
