### ISSUE TITLE
TypeError: (void 0) is not a function at @vue-pdf-viewer_viewer.js?v=c8193675:21033:104

### ISSUE THREAD

**Issue by vuepdfviewer** [vue-pdf-viewer/vue-pdf-viewer#8]
Console displayed error message:
1. TypeError: (void 0) is not a function at @vue-pdf-viewer_viewer.js?v=c8193675:21033:104.

<img width="442" alt="image" src="https://github.com/user-attachments/assets/bdd96d75-4e66-45e0-b206-4a558ddc9f6d">

vite.config.js
```
export default defineConfig({
    optimizeDeps: {
        include: ['pdfjs-dist'],
        esbuildOptions: {
            supported: {
                'top-level-await': true
            },
            target: 'esnext'
        }
    },
...
```

Vue component
```
<template>
    <VPdfViewer
        :workerUrl="pdfWorker"
        :src="pdfUrl"
        initial-scale="1"
    />
</template>

<script>
import { VPdfViewer } from '@vue-pdf-viewer/viewer';
import pdfWorker from 'pdfjs-dist/build/pdf.worker?url';

export default {
    name: "article-pdf",
    components: {
        VPdfViewer
    },
    data() {
        return {
            pdfWorker,
            pdfUrl: 'myUrl',
        }
    },
}
</script>
```

versions
```
"pdfjs-dist": "^4.5.136",
"rimraf": "^6.0.1",
```

_Originally posted by @julsco in https://github.com/vue-pdf-viewer/vue-pdf-viewer/issues/2#issuecomment-2273796305_

**Comment by julsco** [comment]
Hi David,

Thanks for getting back to me. I am off from work until next Monday, I will
try again with the latest version and let you know.

**Comment by julsco** [comment]
I can't reproduce this error anymore, however I now have another error when using the newest version. I have opened a separate issue for that.
